 CREATE TABLE "SCOTT"."STU" 
   (	"ID" NUMBER, 
        "NAME" VARCHAR2(20 BYTE), 
        "STUDATE" DATE
   ) 
   PARTITION  BY RANGE(ID)(--分区PARTITION 通过BY  范围RANGE  的方式
        PARTITION a VALUES LESS THAN (3) TABLESPACE SP215,
        PARTITION b VALUES LESS THAN (5) TABLESPACE SP215,
        PARTITION c VALUES LESS THAN (MAXVALUE) TABLESPACE SP215
    )
    
    
    SELECT * FROM useR_TAB_PARTITIONS WHERE TABLE_NAME='STU';